# Generated by Django 4.0.6 on 2022-07-27 15:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('email_verified', models.BooleanField(default=False, editable=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('password', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('Biography', models.TextField(blank=True, null=True)),
                ('lawyer', models.OneToOneField(limit_choices_to={'email_verified': True}, on_delete=django.db.models.deletion.CASCADE, to='Lawyers.lawyer', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_lawyer', models.CharField(choices=[('Bankruptcy Lawyer', 'Bankruptcy Lawyer'), ('Business Lawyer', 'Business Lawyer'), ('Constitutional Lawyer', 'Constitutional Lawyer'), ('Criminal Defense Lawyer', 'Criminal Defense Lawyer'), ('Employment and Labor Lawyer', 'Employment and Labor Lawyer'), ('Entertainment Lawyer', 'Entertainment Lawyer'), ('Estate Planning Lawyer', 'Entertainment Lawyer'), ('Family Lawyer', 'Family Lawyer'), ('Immigration Lawyer', 'Immigration Lawyer'), ('Intellectual Property', 'Intellectual Property'), ('Personal Injury Lawyer', 'Personal Injury Lawyer'), ('Tax Lawyer', 'Tax Lawyer')], max_length=50, verbose_name='type')),
                ('certificate', models.URLField()),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lawyers.lawyer', to_field='email')),
            ],
            options={
                'verbose_name_plural': 'types',
            },
        ),
    ]
