# Generated by Django 4.0.6 on 2022-07-27 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_of_lawyer',
            field=models.CharField(choices=[('Bankruptcy Lawyer', 'Bankruptcy Lawyer'), ('Business Lawyer', 'Business Lawyer'), ('Constitutional Lawyer', 'Constitutional Lawyer'), ('Criminal Defense Lawyer', 'Criminal Defense Lawyer'), ('Employment and Labor Lawyer', 'Employment and Labor Lawyer'), ('Entertainment Lawyer', 'Entertainment Lawyer'), ('Estate Planning Lawyer', 'Entertainment Lawyer'), ('Family Lawyer', 'Family Lawyer'), ('Immigration Lawyer', 'Immigration Lawyer'), ('Intellectual Property', 'Intellectual Property'), ('Personal Injury Lawyer', 'Personal Injury Lawyer'), ('Tax Lawyer', 'Tax Lawyer')], max_length=50, verbose_name='type_of_lawyer'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('testimony', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lawyers.lawyer')),
            ],
        ),
    ]
