# Generated by Django 4.0.6 on 2022-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyers', '0002_category_verified_alter_category_type_of_lawyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_of_lawyer',
            field=models.CharField(choices=[('Bankruptcy', 'Bankruptcy'), ('Business', 'Business'), ('Constitutional', 'Constitutional'), ('Criminal Defense', 'Criminal Defense'), ('Employment and Labor', 'Employment and Labor'), ('Entertainment', 'Entertainment'), ('Estate Planning', 'Estate Planning'), ('Family', 'Family'), ('Immigration', 'Immigration'), ('Intellectual Property', 'Intellectual Property'), ('Personal Injury', 'Personal Injury'), ('Tax', 'Tax')], max_length=50, verbose_name='type_of_lawyer'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='other_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
