# Generated by Django 4.0.6 on 2022-08-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyers', '0003_alter_category_type_of_lawyer_alter_lawyer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(default='Director', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimony',
            field=models.TextField(blank=True, null=True),
        ),
    ]
