# Generated by Django 4.0.6 on 2022-08-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyers', '0007_bookings_appointment_time_alter_bookings_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], max_length=20)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lawyers.lawyer')),
            ],
        ),
    ]
