# Generated by Django 4.0.6 on 2022-09-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyers', '0010_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lawyers.lawyer')),
            ],
        ),
    ]
